# data_reader.py
"""
Reads and parses aircraft data from a dump1090 JSON feed.

This module is responsible for fetching, validating, and sanitizing aircraft data
from the JSON file generated by dump1090. It performs critical data cleaning,
including type conversion, range validation, and filtering of stale records.
The primary entry point is the `read_aircraft_data` function.
"""

import json
import logging
import os
import time
from typing import Any, Dict, Optional

from config.loader import CONFIG

logger = logging.getLogger(__name__)


def _to_float(v: Any) -> Optional[float]:
    """
    Safely converts a value to a float, returning None on failure.

    Handles a special case where the string "ground" is converted to 0.0, which
    is a convention in dump1090 for barometric altitude.
    """
    try:
        if isinstance(v, str) and v.lower() == 'ground':
            return 0.0
        return float(v)
    except (ValueError, TypeError):
        return None


def _in_range(v: Optional[float], lo: float, hi: float) -> bool:
    """
    Checks if a value is a valid number and falls within a specified range.

    Returns False if the value is None or if it is outside the inclusive range.
    """
    try:
        return lo <= v <= hi
    except TypeError:  # Catches comparison with None
        return False


def read_aircraft_data() -> Dict[str, Dict[str, Any]]:
    """
    Loads, sanitizes, and filters the dump1090 aircraft.json feed.

    This function reads the JSON file specified in the configuration, validates each
    aircraft entry, and returns a clean dictionary of recently seen aircraft.

    Returns:
        A dictionary where keys are the lowercased ICAO hex codes of aircraft.
        Each value is a dictionary containing sanitized and validated fields:
        - `lat`: Latitude in degrees.
        - `lon`: Longitude in degrees.
        - `gs`: Ground speed in knots.
        - `track`: True track in degrees (0-360).
        - `alt`: Altitude in feet. Prefers geometric, falls back to barometric.
        - `vert_rate`: Vertical rate in feet per minute (can be None).
        - `timestamp`: The absolute epoch time of the measurement.
        - `flight`: The flight identifier string (e.g., "SWA123").
        - `age_s`: The age of the position report in seconds, relative to the
                   file's 'now' timestamp.

    Aircraft entries are dropped if they are stale, fail range checks (e.g.,
    invalid latitude), or have missing critical fields like altitude.
    """
    file_path = CONFIG['adsb']['json_file_path']
    max_staleness_s = 10  # Max age of aircraft data to consider valid
    retry_delay_ms = 50   # Delay before retrying after a JSON decode error

    def _load_once() -> Dict[str, Any]:
        """Loads the JSON file once, with specified encoding."""
        with open(file_path, 'r', encoding='utf-8') as f:
            return json.load(f)

    try:
        try:
            data = _load_once()
        except json.JSONDecodeError:
            logger.warning(
                "JSONDecodeError reading %s. Retrying...",
                os.path.basename(file_path)
            )
            time.sleep(retry_delay_ms / 1000.0)
            data = _load_once()

        file_time = _to_float(data.get('now'))
        if file_time is None:
            logger.warning(
                "Missing or invalid 'now' timestamp in %s. Skipping.",
                os.path.basename(file_path)
            )
            return {}

        aircraft_dict = {}
        for ac in data.get('aircraft', []):
            icao_raw = ac.get('hex')
            icao = str(icao_raw).strip().lower() if icao_raw else None
            if not icao:
                continue

            # Determine the age of the last position report
            seen_pos = _to_float(ac.get('seen_pos'))
            age = seen_pos if seen_pos is not None else _to_float(ac.get('seen'))

            if age is None or age > max_staleness_s:
                continue

            # --- Field Extraction and Validation ---
            lat = _to_float(ac.get('lat'))
            lon = _to_float(ac.get('lon'))
            gs = _to_float(ac.get('gs'))
            track = _to_float(ac.get('track'))
            if track == 360.0:
                track = 0.0

            # Prefer geometric altitude, but fall back to barometric
            alt = _to_float(ac.get('alt_geom')) or _to_float(ac.get('alt_baro'))

            # Prefer barometric vertical rate, but fall back to geometric
            vr = (_to_float(ac.get('baro_rate')) or
                  _to_float(ac.get('vert_rate')))

            flight = str(ac.get('flight') or '').strip()

            # --- Sanity Checks ---
            if not _in_range(lat, -90, 90):
                continue
            if not _in_range(lon, -180, 180):
                continue
            if not _in_range(track, 0, 360):
                continue
            if alt is None or not _in_range(alt, -2000, 80000):
                continue
            if not _in_range(gs, 0, 1200):
                continue

            aircraft_dict[icao] = {
                'lat': lat,
                'lon': lon,
                'gs': gs,
                'track': track,
                'alt': alt,
                'vert_rate': vr,
                'timestamp': file_time - age,
                'flight': flight,
                'age_s': age,
            }

        return aircraft_dict

    except FileNotFoundError:
        logger.warning("ADS-B data file not found: %s", file_path)
        return {}
    except json.JSONDecodeError as e:
        logger.error("Failed to decode JSON from %s: %s", file_path, e)
        return {}
    except Exception as e:
        logger.error("Unexpected error in read_aircraft_data: %s", e)
        return {}